# Site settings
title: Scott Walmsley
description: My data science portfolio
highlighter: rouge
#highlighter: pygments.rb
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://scottwalmsley.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Scott Walmsley
user_description: Former bike wrencher and Jack-O-Nothing turned PhD in Cell and Molecular Biology and computer programmer.....how you like 'dem apples?  I currently perform informatic artistry in the world of molecular data analysis combining my right brain creative influx with my left brain discipline.
user_title: Exploring big data in a molecular world
email: scott@metabosoft.com
github_username:  scottwalmsley
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
